import { type Template } from "./types";

export const BUILTIN_TEMPLATES: Template[] = [
  {
    id: "builtin-ise-iade",
    name: "İşe İade Davası",
    category: "İş Hukuku",
    fields: [
      { id: "isci_adi", label: "İşçi Adı Soyadı", type: "text", required: true },
      { id: "isci_tc", label: "TC Kimlik No", type: "text", required: true },
      { id: "isveren", label: "İşveren Unvanı", type: "text", required: true },
      { id: "ise_baslama", label: "İşe Başlama Tarihi", type: "date", required: true },
      { id: "fesih_tarihi", label: "Fesih Tarihi", type: "date", required: true },
      { id: "fesih_sebebi", label: "Bildirilen Fesih Sebebi", type: "textarea", placeholder: "İşveren tarafından belirtilen fesih gerekçesi" },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: İstanbul 3. İş Mahkemesi" },
    ],
  },
  {
    id: "builtin-kidem-tazminati",
    name: "Kıdem Tazminatı Talebi",
    category: "İş Hukuku",
    fields: [
      { id: "isci_adi", label: "İşçi Adı Soyadı", type: "text", required: true },
      { id: "isveren", label: "İşveren Unvanı", type: "text", required: true },
      { id: "calisma_suresi", label: "Çalışma Süresi (yıl)", type: "number", required: true },
      { id: "son_brut_ucret", label: "Son Brüt Ücret (TL)", type: "number", required: true },
      { id: "fesih_tarihi", label: "Fesih Tarihi", type: "date", required: true },
    ],
  },
  {
    id: "builtin-ihbarname",
    name: "Genel İhtarname",
    category: "Ticaret Hukuku",
    fields: [
      { id: "gonderen", label: "Gönderen (Ad Soyad / Unvan)", type: "text", required: true },
      { id: "muhatap", label: "Muhatap (Ad Soyad / Unvan)", type: "text", required: true },
      { id: "konu", label: "İhtar Konusu", type: "text", required: true },
      { id: "aciklama", label: "Açıklama", type: "textarea", required: true, placeholder: "İhtarnamenin detaylı açıklaması" },
      { id: "sure", label: "Verilen Süre (gün)", type: "number", placeholder: "Örn: 7" },
    ],
  },
  {
    id: "builtin-bosanma",
    name: "Anlaşmalı Boşanma Dilekçesi",
    category: "Aile Hukuku",
    fields: [
      { id: "davaci", label: "Davacı Eş", type: "text", required: true },
      { id: "davali", label: "Davalı Eş", type: "text", required: true },
      { id: "evlilik_tarihi", label: "Evlilik Tarihi", type: "date", required: true },
      { id: "cocuk_sayisi", label: "Müşterek Çocuk Sayısı", type: "number" },
      { id: "protokol_ozeti", label: "Anlaşma Protokolü Özeti", type: "textarea", placeholder: "Velayet, nafaka, mal paylaşımı gibi konulardaki anlaşma" },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: İstanbul Aile Mahkemesi" },
    ],
  },
  {
    id: "builtin-nafaka",
    name: "Nafaka Talebi",
    category: "Aile Hukuku",
    fields: [
      { id: "davaci", label: "Davacı", type: "text", required: true },
      { id: "davali", label: "Davalı", type: "text", required: true },
      { id: "nafaka_turu", label: "Nafaka Türü", type: "select", options: ["Tedbir Nafakası", "Yoksulluk Nafakası", "İştirak Nafakası"], required: true },
      { id: "talep_miktari", label: "Talep Edilen Aylık Miktar (TL)", type: "number", required: true },
      { id: "gerekce", label: "Gerekçe", type: "textarea", required: true },
    ],
  },
  {
    id: "builtin-suc-duyurusu",
    name: "Suç Duyurusu",
    category: "Ceza Hukuku",
    fields: [
      { id: "sikayet_eden", label: "Şikayetçi / Müşteki", type: "text", required: true },
      { id: "suphe_li", label: "Şüpheli", type: "text", required: true },
      { id: "suc_tarihi", label: "Suç Tarihi", type: "date", required: true },
      { id: "suc_yeri", label: "Suç Yeri", type: "text" },
      { id: "olay_ozeti", label: "Olay Özeti", type: "textarea", required: true, placeholder: "Olayın ayrıntılı anlatımı" },
      { id: "suc_turu", label: "İsnat Edilen Suç", type: "text", placeholder: "Örn: Dolandırıcılık, Tehdit" },
    ],
  },
  {
    id: "builtin-idari-itiraz",
    name: "İdari İşlem İptali",
    category: "İdare Hukuku",
    fields: [
      { id: "davaci", label: "Davacı", type: "text", required: true },
      { id: "davali_idare", label: "Davalı İdare", type: "text", required: true },
      { id: "islem_tarihi", label: "İşlem Tarihi", type: "date", required: true },
      { id: "islem_konusu", label: "İptali İstenen İşlem", type: "textarea", required: true, placeholder: "İdari işlemin tanımı" },
      { id: "hukuka_aykirilik", label: "Hukuka Aykırılık Gerekçesi", type: "textarea", required: true },
    ],
  },
  {
    id: "builtin-icra-itiraz",
    name: "İcra Takibine İtiraz",
    category: "İcra-İflas",
    fields: [
      { id: "borclu", label: "Borçlu (İtiraz Eden)", type: "text", required: true },
      { id: "alacakli", label: "Alacaklı", type: "text", required: true },
      { id: "dosya_no", label: "İcra Dosya No", type: "text", required: true },
      { id: "itiraz_sebebi", label: "İtiraz Sebebi", type: "select", options: ["Borca İtiraz", "İmzaya İtiraz", "Zamanaşımı İtirazı", "Yetkiye İtiraz"], required: true },
      { id: "aciklama", label: "Açıklama", type: "textarea", required: true },
    ],
  },
  {
    id: "builtin-tuketici-sikayet",
    name: "Tüketici Şikayet Dilekçesi",
    category: "Tüketici Hukuku",
    fields: [
      { id: "tuketici", label: "Tüketici Adı Soyadı", type: "text", required: true },
      { id: "firma", label: "Şikayet Edilen Firma", type: "text", required: true },
      { id: "urun_hizmet", label: "Ürün / Hizmet", type: "text", required: true },
      { id: "satin_alma_tarihi", label: "Satın Alma Tarihi", type: "date" },
      { id: "sorun", label: "Sorun Açıklaması", type: "textarea", required: true, placeholder: "Yaşanan sorunun detaylı açıklaması" },
      { id: "talep", label: "Talep", type: "select", options: ["Ürün İadesi", "Ücretsiz Onarım", "Bedel İadesi", "Ürün Değişimi", "Tazminat"], required: true },
    ],
  },
  {
    id: "builtin-tahliye",
    name: "Tahliye Talepli Dava",
    category: "Gayrimenkul Hukuku",
    fields: [
      { id: "kiraya_veren", label: "Kiraya Veren", type: "text", required: true },
      { id: "kiraci", label: "Kiracı", type: "text", required: true },
      { id: "tasinmaz_adresi", label: "Taşınmaz Adresi", type: "textarea", required: true },
      { id: "kira_baslangic", label: "Kira Başlangıç Tarihi", type: "date" },
      { id: "tahliye_sebebi", label: "Tahliye Sebebi", type: "select", options: ["Kira Bedelinin Ödenmemesi", "Tahliye Taahhüdü", "İhtiyaç Sebebiyle", "Yeniden İnşa/İmar", "Süre Sonu"], required: true },
      { id: "aciklama", label: "Ek Açıklama", type: "textarea" },
    ],
  },
  {
    id: "builtin-ihbar-tazminati",
    name: "İhbar Tazminatı Talebi",
    category: "İş Hukuku",
    fields: [
      { id: "isci_adi", label: "İşçi Adı Soyadı", type: "text", required: true },
      { id: "isveren", label: "İşveren Unvanı", type: "text", required: true },
      { id: "ise_baslama", label: "İşe Başlama Tarihi", type: "date", required: true },
      { id: "fesih_tarihi", label: "Fesih Tarihi", type: "date", required: true },
      { id: "son_brut_ucret", label: "Son Brüt Ücret (TL)", type: "number", required: true },
      { id: "fesih_sekli", label: "Fesih Şekli", type: "select", options: ["İşveren tarafından ihbarsız fesih", "Haklı sebep olmaksızın fesih"], required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: İstanbul 5. İş Mahkemesi" },
    ],
  },
  {
    id: "builtin-fazla-mesai",
    name: "Fazla Mesai Ücreti Alacağı",
    category: "İş Hukuku",
    fields: [
      { id: "isci_adi", label: "İşçi Adı Soyadı", type: "text", required: true },
      { id: "isveren", label: "İşveren Unvanı", type: "text", required: true },
      { id: "calisma_donem", label: "Fazla Mesai Yapılan Dönem", type: "text", required: true, placeholder: "Örn: 01.2023 - 12.2024" },
      { id: "haftalik_saat", label: "Haftalık Ortalama Çalışma Saati", type: "number", required: true, placeholder: "Örn: 55" },
      { id: "son_brut_ucret", label: "Son Brüt Ücret (TL)", type: "number", required: true },
      { id: "odenmis_mi", label: "Fazla Mesai Ücreti Ödenmiş mi?", type: "select", options: ["Hiç ödenmedi", "Kısmen ödendi", "Eksik ödendi"], required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: Ankara 2. İş Mahkemesi" },
    ],
  },
  {
    id: "builtin-yillik-izin",
    name: "Yıllık İzin Ücreti Alacağı",
    category: "İş Hukuku",
    fields: [
      { id: "isci_adi", label: "İşçi Adı Soyadı", type: "text", required: true },
      { id: "isveren", label: "İşveren Unvanı", type: "text", required: true },
      { id: "calisma_suresi", label: "Toplam Çalışma Süresi (yıl)", type: "number", required: true },
      { id: "kullanilmamis_izin", label: "Kullanılmamış İzin Günü", type: "number", required: true },
      { id: "son_brut_ucret", label: "Son Brüt Ücret (TL)", type: "number", required: true },
      { id: "fesih_tarihi", label: "İş Sözleşmesi Sona Erme Tarihi", type: "date", required: true },
    ],
  },
  {
    id: "builtin-mobbing",
    name: "Mobbing (Psikolojik Taciz) Davası",
    category: "İş Hukuku",
    fields: [
      { id: "isci_adi", label: "İşçi Adı Soyadı", type: "text", required: true },
      { id: "isveren", label: "İşveren Unvanı", type: "text", required: true },
      { id: "mobbing_uygulayan", label: "Mobbing Uygulayan Kişi/Pozisyon", type: "text", required: true },
      { id: "baslangic_tarihi", label: "Mobbing Başlangıç Tarihi (yaklaşık)", type: "date" },
      { id: "eylemler", label: "Mobbing Eylemleri", type: "textarea", required: true, placeholder: "Sistematik baskı, dışlama, aşağılama, iş vermeme vb. eylemleri detaylıca yazınız" },
      { id: "saglik_raporu", label: "Sağlık Raporu Var mı?", type: "select", options: ["Evet", "Hayır"] },
      { id: "talep", label: "Talep", type: "select", options: ["Maddi ve Manevi Tazminat", "İş Sözleşmesinin Haklı Feshi + Tazminat", "Sadece Manevi Tazminat"], required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: İstanbul 1. İş Mahkemesi" },
    ],
  },
  {
    id: "builtin-is-kazasi",
    name: "İş Kazası Tazminat Davası",
    category: "İş Hukuku",
    fields: [
      { id: "isci_adi", label: "İşçi / Hak Sahibi Adı Soyadı", type: "text", required: true },
      { id: "isveren", label: "İşveren Unvanı", type: "text", required: true },
      { id: "kaza_tarihi", label: "Kaza Tarihi", type: "date", required: true },
      { id: "kaza_yeri", label: "Kaza Yeri", type: "text", required: true },
      { id: "kaza_aciklama", label: "Kaza Açıklaması", type: "textarea", required: true, placeholder: "Kazanın oluş şekli ve koşulları" },
      { id: "yaralanma", label: "Yaralanma / Maluliyet Durumu", type: "textarea", required: true, placeholder: "Sağlık kurulu raporu, maluliyet oranı vb." },
      { id: "isg_onlem", label: "Alınmayan İSG Önlemleri", type: "textarea", placeholder: "İşverenin almadığı iş sağlığı ve güvenliği önlemleri" },
      { id: "talep_miktari", label: "Talep Edilen Tazminat (TL)", type: "number" },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: Kocaeli 2. İş Mahkemesi" },
    ],
  },
  {
    id: "builtin-sendikal-tazminat",
    name: "Sendikal Tazminat Davası",
    category: "İş Hukuku",
    fields: [
      { id: "isci_adi", label: "İşçi Adı Soyadı", type: "text", required: true },
      { id: "isveren", label: "İşveren Unvanı", type: "text", required: true },
      { id: "sendika", label: "Üye Olunan Sendika", type: "text", required: true },
      { id: "uyelik_tarihi", label: "Sendika Üyelik Tarihi", type: "date", required: true },
      { id: "fesih_tarihi", label: "Fesih Tarihi", type: "date", required: true },
      { id: "fesih_nedeni", label: "İşverenin Bildirdiği Fesih Nedeni", type: "textarea" },
      { id: "sendikal_nedenler", label: "Sendikal Nedenle Fesih Kanıtları", type: "textarea", required: true, placeholder: "Sendika üyeliği sonrası yapılan ayrımcılık, baskı vb." },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: İstanbul 7. İş Mahkemesi" },
    ],
  },
  {
    id: "builtin-sikayet-dilekcesi",
    name: "Şikayet Dilekçesi (Genel)",
    category: "Ceza Hukuku",
    fields: [
      { id: "sikayet_eden", label: "Şikayetçi Adı Soyadı", type: "text", required: true },
      { id: "sikayet_eden_tc", label: "TC Kimlik No", type: "text", required: true },
      { id: "sikayet_eden_adres", label: "Adres", type: "textarea", required: true },
      { id: "supheli", label: "Şüpheli (biliniyorsa)", type: "text", placeholder: "Bilinmiyorsa boş bırakınız" },
      { id: "olay_tarihi", label: "Olay Tarihi", type: "date", required: true },
      { id: "olay_yeri", label: "Olay Yeri", type: "text", required: true },
      { id: "olay_anlatimi", label: "Olayın Ayrıntılı Anlatımı", type: "textarea", required: true },
      { id: "deliller", label: "Deliller", type: "textarea", placeholder: "Tanık, kamera kaydı, belge vb." },
      { id: "cumhuriyet_bassavciligi", label: "Cumhuriyet Başsavcılığı", type: "text", placeholder: "Örn: İstanbul Anadolu Cumhuriyet Başsavcılığı" },
    ],
  },
  {
    id: "builtin-ceza-itiraz",
    name: "Ceza Kararına İtiraz",
    category: "Ceza Hukuku",
    fields: [
      { id: "itiraz_eden", label: "İtiraz Eden (Sanık/Müdafi)", type: "text", required: true },
      { id: "dosya_no", label: "Dosya No", type: "text", required: true },
      { id: "karar_mahkemesi", label: "Kararı Veren Mahkeme", type: "text", required: true },
      { id: "karar_tarihi", label: "Karar Tarihi", type: "date", required: true },
      { id: "karar_ozeti", label: "Karar Özeti", type: "textarea", required: true, placeholder: "Verilen ceza ve mahkumiyet kararının özeti" },
      { id: "itiraz_sebepleri", label: "İtiraz Sebepleri", type: "textarea", required: true, placeholder: "Usul ve esasa ilişkin itiraz gerekçeleri" },
      { id: "talep", label: "Talep", type: "select", options: ["Kararın kaldırılması", "Beraat", "Cezanın indirilmesi", "Yeniden yargılama"], required: true },
    ],
  },
  {
    id: "builtin-temyiz",
    name: "Temyiz Dilekçesi (Ceza)",
    category: "Ceza Hukuku",
    fields: [
      { id: "temyiz_eden", label: "Temyiz Eden", type: "text", required: true },
      { id: "dosya_no", label: "Dosya No", type: "text", required: true },
      { id: "mahkeme", label: "Kararı Veren Mahkeme", type: "text", required: true },
      { id: "karar_tarihi", label: "Karar Tarihi", type: "date", required: true },
      { id: "suc_turu", label: "Suç Türü", type: "text", required: true },
      { id: "verilen_ceza", label: "Verilen Ceza", type: "text", required: true },
      { id: "temyiz_sebepleri", label: "Temyiz Sebepleri", type: "textarea", required: true, placeholder: "CMK md. 288 ve devamı uyarınca temyiz nedenleri" },
      { id: "talep", label: "Talep", type: "select", options: ["Bozma", "Beraat", "Cezanın indirilmesi", "Düşme"], required: true },
    ],
  },
  {
    id: "builtin-beraat-talebi",
    name: "Beraat Talebi (Esas Hakkında Mütalaa)",
    category: "Ceza Hukuku",
    fields: [
      { id: "sanik", label: "Sanık Adı Soyadı", type: "text", required: true },
      { id: "dosya_no", label: "Dosya No", type: "text", required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text", required: true },
      { id: "isnat_edilen_suc", label: "İsnat Edilen Suç", type: "text", required: true },
      { id: "beraat_gerekceleri", label: "Beraat Gerekçeleri", type: "textarea", required: true, placeholder: "Delil yetersizliği, suç unsurlarının oluşmadığı vb." },
      { id: "deliller", label: "Lehe Deliller", type: "textarea", placeholder: "Tanık, belge, bilirkişi raporu vb." },
    ],
  },
  {
    id: "builtin-tutukluluk-itiraz",
    name: "Tutukluluk Kararına İtiraz",
    category: "Ceza Hukuku",
    fields: [
      { id: "supheli_sanik", label: "Şüpheli/Sanık Adı Soyadı", type: "text", required: true },
      { id: "dosya_no", label: "Soruşturma/Dosya No", type: "text", required: true },
      { id: "tutuklama_tarihi", label: "Tutuklama Tarihi", type: "date", required: true },
      { id: "tutuklama_mahkemesi", label: "Tutuklama Kararını Veren Mahkeme", type: "text", required: true },
      { id: "itiraz_sebepleri", label: "İtiraz Sebepleri", type: "textarea", required: true, placeholder: "CMK md. 100 şartlarının bulunmadığı, adli kontrol yeterliliği vb." },
      { id: "talep", label: "Talep", type: "select", options: ["Tahliye", "Adli kontrol tedbirine çevrilmesi", "Ev hapsi"], required: true },
    ],
  },
  {
    id: "builtin-uzlasma",
    name: "Uzlaşma Talebi",
    category: "Ceza Hukuku",
    fields: [
      { id: "talepte_bulunan", label: "Talepte Bulunan", type: "text", required: true },
      { id: "karsi_taraf", label: "Karşı Taraf", type: "text", required: true },
      { id: "dosya_no", label: "Dosya No", type: "text", required: true },
      { id: "suc_turu", label: "Suç Türü", type: "text", required: true, placeholder: "Uzlaşmaya tabi suç türü" },
      { id: "uzlasma_teklifi", label: "Uzlaşma Teklifi", type: "textarea", required: true, placeholder: "Uzlaşma kapsamında önerilen edim (tazminat, özür vb.)" },
      { id: "cumhuriyet_bassavciligi", label: "Cumhuriyet Başsavcılığı", type: "text" },
    ],
  },
  {
    id: "builtin-konkordato",
    name: "Konkordato Talebi",
    category: "Ticaret Hukuku",
    fields: [
      { id: "borclu", label: "Borçlu Şirket Unvanı", type: "text", required: true },
      { id: "borclu_adres", label: "Borçlu Adresi", type: "textarea", required: true },
      { id: "ticaret_sicil_no", label: "Ticaret Sicil No", type: "text", required: true },
      { id: "borc_miktari", label: "Toplam Borç Miktarı (TL)", type: "number", required: true },
      { id: "odeme_guclugu", label: "Ödeme Güçlüğünün Açıklaması", type: "textarea", required: true, placeholder: "Mali durumun kötüleşme nedenleri" },
      { id: "konkordato_projesi", label: "Konkordato Projesi Özeti", type: "textarea", required: true, placeholder: "Alacaklılara önerilen ödeme planı" },
      { id: "mahkeme", label: "Asliye Ticaret Mahkemesi", type: "text", required: true },
    ],
  },
  {
    id: "builtin-alacak-davasi",
    name: "Ticari Alacak Davası",
    category: "Ticaret Hukuku",
    fields: [
      { id: "davaci", label: "Davacı (Alacaklı) Unvanı", type: "text", required: true },
      { id: "davali", label: "Davalı (Borçlu) Unvanı", type: "text", required: true },
      { id: "alacak_miktari", label: "Alacak Miktarı (TL)", type: "number", required: true },
      { id: "alacak_kaynagi", label: "Alacağın Kaynağı", type: "select", options: ["Fatura", "Sözleşme", "Cari hesap", "Çek/Senet", "Haksız fiil"], required: true },
      { id: "vade_tarihi", label: "Vade/Muacceliyet Tarihi", type: "date", required: true },
      { id: "aciklama", label: "Açıklama", type: "textarea", required: true, placeholder: "Alacağın doğuş şekli ve ödenmeme süreci" },
      { id: "faiz_talebi", label: "Faiz Talebi", type: "select", options: ["Avans faizi", "Ticari temerrüt faizi", "Yasal faiz"], required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: İstanbul 3. Asliye Ticaret Mahkemesi" },
    ],
  },
  {
    id: "builtin-haksiz-rekabet",
    name: "Haksız Rekabet Davası",
    category: "Ticaret Hukuku",
    fields: [
      { id: "davaci", label: "Davacı", type: "text", required: true },
      { id: "davali", label: "Davalı", type: "text", required: true },
      { id: "rekabet_eylemi", label: "Haksız Rekabet Eylemi", type: "textarea", required: true, placeholder: "TTK md. 55 kapsamında haksız rekabet oluşturan eylemler" },
      { id: "zarar", label: "Uğranılan Zarar", type: "textarea", required: true },
      { id: "talep", label: "Talep", type: "select", options: ["Tespit + Men + Tazminat", "Tespit + Men", "Sadece Tazminat", "Eski hale iade"], required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: İstanbul Asliye Ticaret Mahkemesi" },
    ],
  },
  {
    id: "builtin-marka-ihlali",
    name: "Marka Hakkına Tecavüz Davası",
    category: "Ticaret Hukuku",
    fields: [
      { id: "davaci", label: "Marka Sahibi / Davacı", type: "text", required: true },
      { id: "davali", label: "İhlal Eden / Davalı", type: "text", required: true },
      { id: "marka_adi", label: "Marka Adı", type: "text", required: true },
      { id: "tescil_no", label: "Marka Tescil No", type: "text", required: true },
      { id: "ihlal_aciklama", label: "İhlal Açıklaması", type: "textarea", required: true, placeholder: "6769 sayılı SMK kapsamında tecavüz oluşturan eylemler" },
      { id: "talep", label: "Talep", type: "select", options: ["Tecavüzün tespiti + men + tazminat", "Tecavüzün tespiti + men", "Tazminat", "Ürünlere el konulması"], required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: İstanbul Fikri ve Sınai Haklar Mahkemesi" },
    ],
  },
  {
    id: "builtin-iflas-erteleme",
    name: "İflas Erteleme Talebi",
    category: "Ticaret Hukuku",
    fields: [
      { id: "sirket", label: "Şirket Unvanı", type: "text", required: true },
      { id: "ticaret_sicil", label: "Ticaret Sicil No", type: "text", required: true },
      { id: "borca_batiklik", label: "Borca Batıklık Durumu", type: "textarea", required: true, placeholder: "Aktif-pasif durumu, borca batıklık bilançosu" },
      { id: "iyilestirme_projesi", label: "İyileştirme Projesi Özeti", type: "textarea", required: true, placeholder: "Şirketin mali durumunu düzeltme planı" },
      { id: "erteleme_suresi", label: "Talep Edilen Erteleme Süresi", type: "select", options: ["1 yıl", "2 yıl", "3 yıl"], required: true },
      { id: "mahkeme", label: "Asliye Ticaret Mahkemesi", type: "text", required: true },
    ],
  },
  {
    id: "builtin-tam-yargi",
    name: "Tam Yargı Davası (İdari Tazminat)",
    category: "İdare Hukuku",
    fields: [
      { id: "davaci", label: "Davacı", type: "text", required: true },
      { id: "davali_idare", label: "Davalı İdare", type: "text", required: true },
      { id: "idari_eylem", label: "Zarara Neden Olan İdari Eylem/İşlem", type: "textarea", required: true },
      { id: "zarar_tarihi", label: "Zarar Tarihi", type: "date", required: true },
      { id: "maddi_zarar", label: "Maddi Zarar Miktarı (TL)", type: "number" },
      { id: "manevi_zarar", label: "Manevi Tazminat Talebi (TL)", type: "number" },
      { id: "zarar_aciklama", label: "Zarar Açıklaması", type: "textarea", required: true, placeholder: "İdarenin kusurlu eylemi ve nedensellik bağı" },
      { id: "mahkeme", label: "İdare Mahkemesi", type: "text", placeholder: "Örn: Ankara 4. İdare Mahkemesi" },
    ],
  },
  {
    id: "builtin-yurutmeyi-durdurma",
    name: "Yürütmeyi Durdurma Talebi",
    category: "İdare Hukuku",
    fields: [
      { id: "davaci", label: "Davacı", type: "text", required: true },
      { id: "davali_idare", label: "Davalı İdare", type: "text", required: true },
      { id: "islem", label: "İptali İstenen İdari İşlem", type: "textarea", required: true },
      { id: "islem_tarihi", label: "İşlem Tarihi", type: "date", required: true },
      { id: "teblig_tarihi", label: "Tebliğ Tarihi", type: "date", required: true },
      { id: "hukuka_aykirilik", label: "Açıkça Hukuka Aykırılık Gerekçesi", type: "textarea", required: true, placeholder: "İYUK md. 27 - hukuka açıkça aykırılık" },
      { id: "telafisi_guc_zarar", label: "Telafisi Güç veya İmkansız Zarar", type: "textarea", required: true, placeholder: "İşlemin uygulanması halinde doğacak telafisi güç zararlar" },
      { id: "mahkeme", label: "İdare Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-idari-basvuru",
    name: "İdari Başvuru Dilekçesi",
    category: "İdare Hukuku",
    fields: [
      { id: "basvuran", label: "Başvuran Adı Soyadı", type: "text", required: true },
      { id: "basvuran_tc", label: "TC Kimlik No", type: "text", required: true },
      { id: "basvurulan_idare", label: "Başvurulan İdare/Kurum", type: "text", required: true },
      { id: "basvuru_konusu", label: "Başvuru Konusu", type: "textarea", required: true, placeholder: "Talep edilen idari işlem veya düzeltme" },
      { id: "gerekce", label: "Gerekçe ve Yasal Dayanak", type: "textarea", required: true },
      { id: "ekler", label: "Ek Belgeler", type: "textarea", placeholder: "Başvuruya eklenen belgelerin listesi" },
    ],
  },
  {
    id: "builtin-bilgi-edinme",
    name: "Bilgi Edinme Başvurusu",
    category: "İdare Hukuku",
    fields: [
      { id: "basvuran", label: "Başvuran Adı Soyadı", type: "text", required: true },
      { id: "basvuran_tc", label: "TC Kimlik No", type: "text", required: true },
      { id: "basvuran_adres", label: "Adres", type: "textarea", required: true },
      { id: "basvurulan_kurum", label: "Başvurulan Kurum", type: "text", required: true },
      { id: "bilgi_konusu", label: "Talep Edilen Bilgi/Belge", type: "textarea", required: true, placeholder: "4982 sayılı Bilgi Edinme Hakkı Kanunu kapsamında talep edilen bilgi veya belge" },
      { id: "amac", label: "Bilgi Edinme Amacı", type: "textarea" },
    ],
  },
  {
    id: "builtin-cekismeli-bosanma",
    name: "Çekişmeli Boşanma Davası",
    category: "Aile Hukuku",
    fields: [
      { id: "davaci", label: "Davacı Eş", type: "text", required: true },
      { id: "davaci_tc", label: "Davacı TC Kimlik No", type: "text", required: true },
      { id: "davali", label: "Davalı Eş", type: "text", required: true },
      { id: "evlilik_tarihi", label: "Evlilik Tarihi", type: "date", required: true },
      { id: "cocuk_bilgileri", label: "Müşterek Çocuk Bilgileri", type: "textarea", placeholder: "İsim, doğum tarihi" },
      { id: "bosanma_sebebi", label: "Boşanma Sebebi", type: "select", options: ["Evlilik birliğinin temelinden sarsılması (TMK 166/1)", "Zina (TMK 161)", "Hayata kast, pek kötü muamele (TMK 162)", "Terk (TMK 164)", "Akıl hastalığı (TMK 165)", "Suç işleme ve haysiyetsiz hayat sürme (TMK 163)"], required: true },
      { id: "olaylar", label: "Olayların Anlatımı", type: "textarea", required: true, placeholder: "Boşanmaya neden olan olayların kronolojik anlatımı" },
      { id: "talepler", label: "Talepler", type: "textarea", required: true, placeholder: "Velayet, nafaka, tazminat, mal paylaşımı talepleri" },
      { id: "mahkeme", label: "Aile Mahkemesi", type: "text", placeholder: "Örn: İstanbul 5. Aile Mahkemesi" },
    ],
  },
  {
    id: "builtin-velayet",
    name: "Velayet Davası",
    category: "Aile Hukuku",
    fields: [
      { id: "davaci", label: "Davacı (Velayet Talep Eden)", type: "text", required: true },
      { id: "davali", label: "Davalı", type: "text", required: true },
      { id: "cocuk_adi", label: "Çocuğun Adı Soyadı", type: "text", required: true },
      { id: "cocuk_dogum", label: "Çocuğun Doğum Tarihi", type: "date", required: true },
      { id: "mevcut_velayet", label: "Mevcut Velayet Durumu", type: "text", required: true },
      { id: "velayet_degisiklik_sebebi", label: "Velayet Değişikliği Gerekçesi", type: "textarea", required: true, placeholder: "TMK md. 183, 348 - çocuğun üstün yararı kapsamında değişiklik gerekçesi" },
      { id: "mahkeme", label: "Aile Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-mal-paylasimi",
    name: "Mal Paylaşımı (Mal Rejimi Tasfiyesi) Davası",
    category: "Aile Hukuku",
    fields: [
      { id: "davaci", label: "Davacı", type: "text", required: true },
      { id: "davali", label: "Davalı", type: "text", required: true },
      { id: "evlilik_tarihi", label: "Evlilik Tarihi", type: "date", required: true },
      { id: "bosanma_tarihi", label: "Boşanma Karar Tarihi", type: "date", required: true },
      { id: "mal_rejimi", label: "Uygulanan Mal Rejimi", type: "select", options: ["Edinilmiş mallara katılma (yasal)", "Mal ayrılığı", "Paylaşmalı mal ayrılığı", "Mal ortaklığı"], required: true },
      { id: "mallar", label: "Tasfiyeye Konu Malvarlığı Değerleri", type: "textarea", required: true, placeholder: "Taşınmazlar, araçlar, banka hesapları, şirket hisseleri vb." },
      { id: "talep_miktari", label: "Katılma Alacağı Talebi (TL)", type: "number" },
      { id: "mahkeme", label: "Aile Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-koruma-karari",
    name: "Koruma Kararı Talebi (6284 Sayılı Kanun)",
    category: "Aile Hukuku",
    fields: [
      { id: "basvuran", label: "Başvuran Adı Soyadı", type: "text", required: true },
      { id: "basvuran_tc", label: "TC Kimlik No", type: "text", required: true },
      { id: "siddet_uygulayan", label: "Şiddet Uygulayan", type: "text", required: true },
      { id: "yakinlik", label: "Yakınlık Derecesi", type: "select", options: ["Eş", "Eski eş", "Birlikte yaşayan", "Aile üyesi", "Diğer"], required: true },
      { id: "siddet_turu", label: "Şiddet Türü", type: "select", options: ["Fiziksel şiddet", "Psikolojik şiddet", "Ekonomik şiddet", "Cinsel şiddet", "Birden fazla"], required: true },
      { id: "olaylar", label: "Olayların Anlatımı", type: "textarea", required: true },
      { id: "talep_edilen_tedbirler", label: "Talep Edilen Tedbirler", type: "textarea", required: true, placeholder: "Uzaklaştırma, iletişim yasağı, barınma yardımı vb." },
    ],
  },
  {
    id: "builtin-itirazin-iptali",
    name: "İtirazın İptali Davası",
    category: "İcra-İflas",
    fields: [
      { id: "davaci", label: "Davacı (Alacaklı)", type: "text", required: true },
      { id: "davali", label: "Davalı (Borçlu)", type: "text", required: true },
      { id: "icra_dosya_no", label: "İcra Dosya No", type: "text", required: true },
      { id: "alacak_miktari", label: "Takip Miktarı (TL)", type: "number", required: true },
      { id: "alacak_sebebi", label: "Alacağın Sebebi", type: "textarea", required: true },
      { id: "itiraz_tarihi", label: "Borçlunun İtiraz Tarihi", type: "date", required: true },
      { id: "icra_inkar_tazminati", label: "İcra İnkar Tazminatı Talebi", type: "select", options: ["Evet (%20'den aşağı olmamak üzere)", "Hayır"], required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text", placeholder: "Örn: İstanbul 1. Asliye Hukuk Mahkemesi" },
    ],
  },
  {
    id: "builtin-itirazin-kaldirilmasi",
    name: "İtirazın Kaldırılması Talebi",
    category: "İcra-İflas",
    fields: [
      { id: "alacakli", label: "Alacaklı", type: "text", required: true },
      { id: "borclu", label: "Borçlu", type: "text", required: true },
      { id: "icra_dosya_no", label: "İcra Dosya No", type: "text", required: true },
      { id: "belge_turu", label: "Dayanak Belge", type: "select", options: ["İmza adi veya resmi senet", "Resmi dairelerin veya yetkili makamların belgeleri", "Kredi sözleşmesi", "Diğer İİK 68 belgesi"], required: true },
      { id: "alacak_miktari", label: "Alacak Miktarı (TL)", type: "number", required: true },
      { id: "aciklama", label: "Açıklama", type: "textarea", required: true },
      { id: "icra_mahkemesi", label: "İcra Hukuk Mahkemesi", type: "text", required: true },
    ],
  },
  {
    id: "builtin-menfi-tespit",
    name: "Menfi Tespit Davası",
    category: "İcra-İflas",
    fields: [
      { id: "davaci", label: "Davacı (Borçlu)", type: "text", required: true },
      { id: "davali", label: "Davalı (Alacaklı)", type: "text", required: true },
      { id: "icra_dosya_no", label: "İcra Dosya No", type: "text" },
      { id: "borc_miktari", label: "İddia Edilen Borç Miktarı (TL)", type: "number", required: true },
      { id: "borclu_olmama_sebebi", label: "Borçlu Olmama Sebebi", type: "textarea", required: true, placeholder: "Ödeme, zamanaşımı, sahtecilik, takas vb." },
      { id: "ihtiyati_tedbir", label: "İhtiyati Tedbir Talebi", type: "select", options: ["Evet (icranın durdurulması)", "Hayır"], required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text" },
    ],
  },
  {
    id: "builtin-istirdat",
    name: "İstirdat Davası",
    category: "İcra-İflas",
    fields: [
      { id: "davaci", label: "Davacı (Ödeme Yapan)", type: "text", required: true },
      { id: "davali", label: "Davalı (Tahsil Eden)", type: "text", required: true },
      { id: "icra_dosya_no", label: "İcra Dosya No", type: "text", required: true },
      { id: "odenen_miktar", label: "Ödenen/Tahsil Edilen Miktar (TL)", type: "number", required: true },
      { id: "odeme_tarihi", label: "Ödeme Tarihi", type: "date", required: true },
      { id: "iade_sebebi", label: "İade Gerekçesi", type: "textarea", required: true, placeholder: "Borçlu olunmadığı halde ödeme yapıldığına dair gerekçe" },
      { id: "mahkeme", label: "Mahkeme", type: "text" },
    ],
  },
  {
    id: "builtin-haciz-istemi",
    name: "Haciz Talebi",
    category: "İcra-İflas",
    fields: [
      { id: "alacakli", label: "Alacaklı", type: "text", required: true },
      { id: "borclu", label: "Borçlu", type: "text", required: true },
      { id: "icra_dosya_no", label: "İcra Dosya No", type: "text", required: true },
      { id: "alacak_miktari", label: "Alacak Miktarı (TL)", type: "number", required: true },
      { id: "haciz_turu", label: "Haciz Türü", type: "select", options: ["Menkul haczi", "Gayrimenkul haczi", "Banka hesabı haczi", "Maaş haczi", "Araç haczi"], required: true },
      { id: "haciz_adresi", label: "Haciz Yapılacak Adres/Bilgi", type: "textarea", required: true },
      { id: "icra_dairesi", label: "İcra Dairesi", type: "text", required: true },
    ],
  },
  {
    id: "builtin-iflas-talebi",
    name: "İflas Davası",
    category: "İcra-İflas",
    fields: [
      { id: "davaci", label: "Davacı (Alacaklı)", type: "text", required: true },
      { id: "davali", label: "Davalı (Borçlu Tacir)", type: "text", required: true },
      { id: "alacak_miktari", label: "Alacak Miktarı (TL)", type: "number", required: true },
      { id: "iflas_sebebi", label: "İflas Sebebi", type: "select", options: ["Ödeme emrine itiraz edilmemesi (İİK 155)", "Alacağın icra takibinde tahsil edilememesi", "Borçlunun aciz hali"], required: true },
      { id: "icra_dosya_no", label: "İcra Dosya No (varsa)", type: "text" },
      { id: "aciklama", label: "Açıklama", type: "textarea", required: true },
      { id: "mahkeme", label: "Asliye Ticaret Mahkemesi", type: "text", required: true },
    ],
  },
  {
    id: "builtin-ayipli-mal",
    name: "Ayıplı Mal Davası",
    category: "Tüketici Hukuku",
    fields: [
      { id: "davaci", label: "Davacı (Tüketici)", type: "text", required: true },
      { id: "davali", label: "Davalı (Satıcı/Üretici)", type: "text", required: true },
      { id: "urun", label: "Ürün Adı ve Markası", type: "text", required: true },
      { id: "satin_alma_tarihi", label: "Satın Alma Tarihi", type: "date", required: true },
      { id: "fatura_bedeli", label: "Fatura Bedeli (TL)", type: "number", required: true },
      { id: "ayip_aciklama", label: "Ayıp Açıklaması", type: "textarea", required: true, placeholder: "6502 sayılı TKHK md. 8 - üründeki ayıbın detaylı açıklaması" },
      { id: "basvuru_yapildi_mi", label: "Satıcıya/Yetkili Servise Başvuruldu mu?", type: "select", options: ["Evet", "Hayır"], required: true },
      { id: "talep", label: "Talep (Seçimlik Hak)", type: "select", options: ["Ücretsiz onarım", "Ürün değişimi", "Bedel iadesi", "Bedelden indirim"], required: true },
      { id: "mahkeme", label: "Tüketici Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-cayma-hakki",
    name: "Cayma Hakkı Kullanımı",
    category: "Tüketici Hukuku",
    fields: [
      { id: "tuketici", label: "Tüketici Adı Soyadı", type: "text", required: true },
      { id: "tuketici_adres", label: "Adres", type: "textarea", required: true },
      { id: "satici", label: "Satıcı Firma", type: "text", required: true },
      { id: "siparis_tarihi", label: "Sipariş/Sözleşme Tarihi", type: "date", required: true },
      { id: "teslim_tarihi", label: "Teslim Tarihi", type: "date", required: true },
      { id: "urun_hizmet", label: "Ürün/Hizmet", type: "text", required: true },
      { id: "bedel", label: "Ödenen Bedel (TL)", type: "number", required: true },
      { id: "cayma_sebebi", label: "Cayma Sebebi (Opsiyonel)", type: "textarea", placeholder: "Mesafeli sözleşmelerde sebep göstermek zorunlu değildir" },
    ],
  },
  {
    id: "builtin-tuketici-hakem",
    name: "Tüketici Hakem Heyeti Başvurusu",
    category: "Tüketici Hukuku",
    fields: [
      { id: "basvuran", label: "Başvuran (Tüketici)", type: "text", required: true },
      { id: "basvuran_tc", label: "TC Kimlik No", type: "text", required: true },
      { id: "basvuran_adres", label: "Adres", type: "textarea", required: true },
      { id: "basvuran_tel", label: "Telefon", type: "text" },
      { id: "satici", label: "Şikayet Edilen Firma", type: "text", required: true },
      { id: "satici_adres", label: "Firma Adresi", type: "textarea" },
      { id: "urun_hizmet", label: "Ürün/Hizmet", type: "text", required: true },
      { id: "satin_alma_tarihi", label: "Satın Alma Tarihi", type: "date" },
      { id: "tutar", label: "İşlem Tutarı (TL)", type: "number", required: true },
      { id: "sikayet", label: "Şikayet Konusu", type: "textarea", required: true, placeholder: "Yaşanan sorunun detaylı anlatımı" },
      { id: "talep", label: "Talep", type: "textarea", required: true, placeholder: "Tüketici olarak talebiniz" },
    ],
  },
  {
    id: "builtin-kira-tespit",
    name: "Kira Tespit Davası",
    category: "Gayrimenkul Hukuku",
    fields: [
      { id: "davaci", label: "Davacı (Kiraya Veren)", type: "text", required: true },
      { id: "davali", label: "Davalı (Kiracı)", type: "text", required: true },
      { id: "tasinmaz_adresi", label: "Taşınmaz Adresi", type: "textarea", required: true },
      { id: "mevcut_kira", label: "Mevcut Aylık Kira (TL)", type: "number", required: true },
      { id: "talep_edilen_kira", label: "Talep Edilen Aylık Kira (TL)", type: "number", required: true },
      { id: "kira_baslangic", label: "Kira Başlangıç Tarihi", type: "date", required: true },
      { id: "emsal_kiralar", label: "Emsal Kira Bedelleri", type: "textarea", placeholder: "Çevredeki emsal taşınmazların kira bedelleri" },
      { id: "mahkeme", label: "Sulh Hukuk Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-kira-uyarlama",
    name: "Kira Uyarlama Davası",
    category: "Gayrimenkul Hukuku",
    fields: [
      { id: "davaci", label: "Davacı", type: "text", required: true },
      { id: "davali", label: "Davalı", type: "text", required: true },
      { id: "tasinmaz_adresi", label: "Taşınmaz Adresi", type: "textarea", required: true },
      { id: "mevcut_kira", label: "Mevcut Aylık Kira (TL)", type: "number", required: true },
      { id: "uyarlama_sebebi", label: "Uyarlama Sebebi", type: "select", options: ["Aşırı ifa güçlüğü (TBK md. 138)", "Ekonomik kriz / enflasyon", "Taşınmazın değer kaybı", "Diğer olağanüstü değişiklik"], required: true },
      { id: "aciklama", label: "Uyarlama Gerekçesi", type: "textarea", required: true, placeholder: "Sözleşmenin kurulduğu andaki koşulların öngörülemez biçimde değiştiği" },
      { id: "talep_edilen_kira", label: "Talep Edilen Yeni Kira (TL)", type: "number" },
      { id: "mahkeme", label: "Sulh Hukuk Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-depozito-iade",
    name: "Depozito İadesi Talebi",
    category: "Gayrimenkul Hukuku",
    fields: [
      { id: "kiraci", label: "Kiracı (Talep Eden)", type: "text", required: true },
      { id: "kiraya_veren", label: "Kiraya Veren", type: "text", required: true },
      { id: "tasinmaz_adresi", label: "Taşınmaz Adresi", type: "textarea", required: true },
      { id: "kira_baslangic", label: "Kira Başlangıç Tarihi", type: "date", required: true },
      { id: "tahliye_tarihi", label: "Tahliye Tarihi", type: "date", required: true },
      { id: "depozito_miktari", label: "Depozito Miktarı (TL)", type: "number", required: true },
      { id: "iade_yapildi_mi", label: "İade Yapıldı mı?", type: "select", options: ["Hiç iade yapılmadı", "Kısmen iade yapıldı", "Haksız kesinti yapıldı"], required: true },
      { id: "aciklama", label: "Ek Açıklama", type: "textarea" },
    ],
  },
  {
    id: "builtin-tazminat-genel",
    name: "Maddi ve Manevi Tazminat Davası",
    category: "Borçlar Hukuku",
    fields: [
      { id: "davaci", label: "Davacı", type: "text", required: true },
      { id: "davali", label: "Davalı", type: "text", required: true },
      { id: "olay_tarihi", label: "Olay Tarihi", type: "date", required: true },
      { id: "olay_ozeti", label: "Olayın Özeti", type: "textarea", required: true, placeholder: "Haksız fiil veya sözleşmeye aykırılık" },
      { id: "maddi_zarar", label: "Maddi Tazminat Talebi (TL)", type: "number" },
      { id: "manevi_zarar", label: "Manevi Tazminat Talebi (TL)", type: "number" },
      { id: "zarar_detay", label: "Zarar Detayı", type: "textarea", required: true, placeholder: "Uğranılan zararın detaylı açıklaması ve belgeleri" },
      { id: "hukuki_dayanak", label: "Hukuki Dayanak", type: "select", options: ["Haksız fiil (TBK md. 49-76)", "Sözleşmeye aykırılık (TBK md. 112)", "Vekaletsiz iş görme", "Tehlike sorumluluğu"], required: true },
      { id: "mahkeme", label: "Mahkeme", type: "text" },
    ],
  },
  {
    id: "builtin-miras-tenkis",
    name: "Tenkis Davası (Miras)",
    category: "Miras Hukuku",
    fields: [
      { id: "davaci", label: "Davacı (Saklı Paylı Mirasçı)", type: "text", required: true },
      { id: "davali", label: "Davalı", type: "text", required: true },
      { id: "muris", label: "Muris (Ölen)", type: "text", required: true },
      { id: "olum_tarihi", label: "Ölüm Tarihi", type: "date", required: true },
      { id: "sakli_pay_orani", label: "Saklı Pay Oranı", type: "text", required: true, placeholder: "Örn: 1/4, 1/2" },
      { id: "tenkise_konu_islem", label: "Tenkise Konu Tasarruf", type: "textarea", required: true, placeholder: "Vasiyetname, bağışlama, ölünceye kadar bakma sözleşmesi vb." },
      { id: "mahkeme", label: "Asliye Hukuk Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-miras-paylasimi",
    name: "Miras Paylaşımı (Ortaklığın Giderilmesi)",
    category: "Miras Hukuku",
    fields: [
      { id: "davaci", label: "Davacı (Mirasçı)", type: "text", required: true },
      { id: "davalilar", label: "Davalılar (Diğer Mirasçılar)", type: "textarea", required: true },
      { id: "muris", label: "Muris (Ölen)", type: "text", required: true },
      { id: "olum_tarihi", label: "Ölüm Tarihi", type: "date", required: true },
      { id: "tereke", label: "Tereke Malvarlığı", type: "textarea", required: true, placeholder: "Taşınmazlar, araçlar, banka hesapları vb." },
      { id: "paylasim_talebi", label: "Paylaşım Talebi", type: "select", options: ["Aynen taksim", "Satış yoluyla taksim", "Karma"], required: true },
      { id: "mahkeme", label: "Sulh Hukuk Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-kamulaştırma-bedel",
    name: "Kamulaştırma Bedel Artırım Davası",
    category: "Gayrimenkul Hukuku",
    fields: [
      { id: "davaci", label: "Davacı (Taşınmaz Sahibi)", type: "text", required: true },
      { id: "davali_idare", label: "Davalı (Kamulaştıran İdare)", type: "text", required: true },
      { id: "tasinmaz", label: "Taşınmaz Bilgileri (Ada/Parsel)", type: "text", required: true },
      { id: "tasinmaz_adresi", label: "Taşınmaz Adresi", type: "textarea", required: true },
      { id: "takdir_edilen_bedel", label: "İdarece Takdir Edilen Bedel (TL)", type: "number", required: true },
      { id: "talep_edilen_bedel", label: "Talep Edilen Bedel (TL)", type: "number", required: true },
      { id: "bedel_farki_gerekce", label: "Bedel Farkı Gerekçesi", type: "textarea", required: true, placeholder: "Emsal satışlar, bilirkişi tespitleri, imar durumu vb." },
      { id: "mahkeme", label: "Asliye Hukuk Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-tapu-iptal-tescil",
    name: "Tapu İptali ve Tescil Davası",
    category: "Gayrimenkul Hukuku",
    fields: [
      { id: "davaci", label: "Davacı", type: "text", required: true },
      { id: "davali", label: "Davalı (Tapuda Kayıtlı Malik)", type: "text", required: true },
      { id: "tasinmaz", label: "Taşınmaz Bilgileri (Ada/Parsel/Pafta)", type: "text", required: true },
      { id: "tapu_iptal_sebebi", label: "Tapu İptal Sebebi", type: "select", options: ["Muris muvazaası", "Ehliyetsizlik", "Hukuki ehliyetsizlik", "Vekalet görevinin kötüye kullanılması", "Hata/Hile/İkrah", "Sahtecilik"], required: true },
      { id: "aciklama", label: "Dava Gerekçesi", type: "textarea", required: true },
      { id: "mahkeme", label: "Asliye Hukuk Mahkemesi", type: "text" },
    ],
  },
  {
    id: "builtin-istinaf",
    name: "İstinaf Başvuru Dilekçesi",
    category: "Usul Hukuku",
    fields: [
      { id: "istinaf_eden", label: "İstinaf Eden", type: "text", required: true },
      { id: "karsi_taraf", label: "Karşı Taraf", type: "text", required: true },
      { id: "ilk_derece_mahkemesi", label: "İlk Derece Mahkemesi", type: "text", required: true },
      { id: "dosya_no", label: "Dosya No", type: "text", required: true },
      { id: "karar_tarihi", label: "Karar Tarihi", type: "date", required: true },
      { id: "teblig_tarihi", label: "Tebliğ Tarihi", type: "date", required: true },
      { id: "karar_ozeti", label: "Kararın Özeti", type: "textarea", required: true },
      { id: "istinaf_sebepleri", label: "İstinaf Sebepleri", type: "textarea", required: true, placeholder: "HMK md. 353-355 kapsamında istinaf nedenleri" },
      { id: "talep", label: "Talep", type: "select", options: ["Kararın kaldırılması ve davanın kabulü", "Kararın kaldırılması ve yeniden yargılama", "Kararın düzeltilerek kaldırılması"], required: true },
      { id: "bam", label: "Bölge Adliye Mahkemesi", type: "text", placeholder: "Örn: İstanbul BAM 12. Hukuk Dairesi" },
    ],
  },
  {
    id: "builtin-ihtiyati-tedbir",
    name: "İhtiyati Tedbir Talebi",
    category: "Usul Hukuku",
    fields: [
      { id: "davaci", label: "Davacı / Talep Eden", type: "text", required: true },
      { id: "davali", label: "Davalı / Aleyhine İstenen", type: "text", required: true },
      { id: "dava_konusu", label: "Dava Konusu", type: "textarea", required: true },
      { id: "tedbir_konusu", label: "Tedbir Konusu", type: "textarea", required: true, placeholder: "HMK md. 389 - dava konusunun tehlikeye düşmesi veya hakkın elde edilmesinin zorlaşması" },
      { id: "tedbir_sebebi", label: "Tedbir Sebebi (Yakın Tehlike)", type: "textarea", required: true },
      { id: "talep_edilen_tedbir", label: "Talep Edilen Tedbir", type: "textarea", required: true, placeholder: "Satışın önlenmesi, üzerine şerh konulması vb." },
      { id: "mahkeme", label: "Mahkeme", type: "text" },
    ],
  },
  {
    id: "builtin-vergi-itiraz",
    name: "Vergi Cezasına İtiraz",
    category: "Vergi Hukuku",
    fields: [
      { id: "davaci", label: "Davacı (Mükellef)", type: "text", required: true },
      { id: "davaci_vkn", label: "Vergi Kimlik No", type: "text", required: true },
      { id: "davali", label: "Davalı (Vergi Dairesi)", type: "text", required: true },
      { id: "ihbarname_tarihi", label: "İhbarname Tarihi", type: "date", required: true },
      { id: "ihbarname_no", label: "İhbarname No", type: "text", required: true },
      { id: "vergi_turu", label: "Vergi Türü", type: "select", options: ["Gelir Vergisi", "Kurumlar Vergisi", "KDV", "ÖTV", "MTV", "Diğer"], required: true },
      { id: "tarhiyat_miktari", label: "Tarhiyat/Ceza Miktarı (TL)", type: "number", required: true },
      { id: "itiraz_sebepleri", label: "İtiraz Sebepleri", type: "textarea", required: true, placeholder: "VUK ve ilgili kanun maddeleri kapsamında itiraz gerekçeleri" },
      { id: "mahkeme", label: "Vergi Mahkemesi", type: "text" },
    ],
  },
];
